### ISSUE TITLE
Function for getting raven loc returning wrong path

### ISSUE THREAD

**Issue by caleb-sitton-inl** [idaholab/DOVE#1]
The `src._utils.get_raven_loc()` function sometimes returns the path to the `ravenframework` directory instead of the path to the `raven` directory. In line 17 of the `src._utils` file, `importlib.util.find_spec()` is used to find the location of the `ravenframework` directory. If successful, this location is accessed in line 19 with `spec.origin`, and the path to its parent directory is then returned. It would seem that `spec.origin` is expected to be a path to the `ravenframework` directory (hence returning the path to the `raven` directory); however, since `ravenframework` is a package, the `.origin` attribute instead refers to the `ravenframework/__init__.py` file. Thus `get_raven_loc()` returns the path to the parent directory of the `__init__.py` file, which is the path to `ravenframework`. This would seem to be the cause of the issue.

**Comment by dylanjm** [comment]
I don't know if that an actual issue or not? The purpose of the `get_raven_loc()` is to find where the raven library is located and add it to the PYTHONPATH. If it has been pip installed then we expect the library to be located within `site-packages/ravenframework/` if it's been cloned locally then we expect the library to be located within the `raven/` directory.

**Comment by caleb-sitton-inl** [comment]
@dylanjm My understanding of the comment at the end is that it explains that since ravenframework can be installed as a package, a more general form needs to be added to the PYTHONPATH than was used in a previous version of raven. In the context of the `HERON/src/_utils.py` file, from which I believe this comment comes, there are two return statements for heron's version of `get_raven_loc`. The first, in line 47, returns the directory component of the path to the imported package `ravenframework` (which is the path to `raven`). The second, in line 61, returns the directory component of the path held in the `FrameworkLocation` node in the `.ravenconfig` file. I believe this should also be the path to `raven`.

In my particular application of the `get_raven_loc` function, I am using it to find the `raven` directory so I can find `run_tests`, which is the same methodology I used in HERON for the `HERON/coverage_scripts/check_py_coverage.sh` script. I'm not sure if this was the intended use of the `get_raven_loc` function, but it is quite helpful for this.

**Comment by caleb-sitton-inl** [comment]
@dylanjm I'm not understanding how the DOVE `get_raven_loc()` returns the same information as the HERON `get_raven_loc()`. If I understand correctly, the return statement line 19 of the DOVE `src/_utils.py` is designed to mirror the return statement in line 47 (in the first block) of HERON `src/_utils.py`. Here's a screenshot of what those python commands are returning for me.

![Screenshot 2024-10-22 121717](https://github.com/user-attachments/assets/c4ed2bf5-b2d1-414e-98f0-19c3f4ed344e)

Since the HERON function returns the `path.dirname()` of the `ravenframework` directory, and DOVE returns the `path.dirname()` of the `__init__.py` file, the return values seem to be off by one level. The documentation I've referred to on each of the methodologies is in section 6.4.3 of [https://docs.python.org/3/tutorial/modules.html](url) (for HERON) and [https://docs.python.org/3/library/importlib.html#importlib.machinery.ModuleSpec.origin](url) (for DOVE).

If this is how HERON's `get_raven_loc()` normally works, I am thoroughly confused regarding how this function could work in HERON with the pip installation of `ravenframework`.

Yes, here's a screenshot of my desired usage of the `get_raven_loc()` function. See lines 5 and 19.

![Screenshot 2024-10-22 124056](https://github.com/user-attachments/assets/9de4fceb-0868-4e3e-9696-97367c8120c5)

**Comment by PaulTalbot-INL** [comment]
Just to add my two cents here, when we started designing the Plugin system for RAVEN, we intended to use the `raven/plugins_directory.xml` to store locations of all installed plugins, and when a plugin is installed, to edit the `.ravenconfig.xml` file in the base level of the plugin to point to where the associated RAVEN is. In the HERON on my machine, this points to the `ravenframework` folder, e.g.,:
```xml
$cat .ravenconfig.xml
<RavenConfig>
  <FrameworkLocation>C:\Users\TALBPW\projects\raven\ravenframework</FrameworkLocation>
</RavenConfig>
```

**Comment by dylanjm** [comment]
@caleb-sitton-inl I think I see where the confusion is arising from. It appears you have manually added ravenframework to your PYTHONPATH which is why you're getting a return in the first if-block of DOVE. This is not default behavior if you have a local version of `raven` cloned onto your computer. 

If a user has pip installed raven, they only have access to the `ravenframework` folder and do **not** have access to `run_tests` so the coverage script should only be ran by developers working on a local version of RAVEN. So there is an implicit assumption that if you need access to developer tools, you are not using the pip version of RAVEN. 

So for example, suppose I have pip installed raven, here is a replication of your code up above:

```
pip install raven-framework==3.1
python
>>> import importlib
>>> spec = importlib.util.find_spec("ravenframework")
>>> spec.origin
'/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/__init__.py'
```
Notice how there is no top-level `raven` folder that contains all the typical developer tools. It's only the python code itself that is shipped with the pip install. 

So I don't think `get_raven_loc()` has the issue, it's probably the __init__.py files for unit-test folder that needs to be smarter on how to import `ravenframework` 

If you have questions, let's set up a Teams meeting.

**Comment by caleb-sitton-inl** [comment]
@dylanjm Okay, that makes a lot more sense. It still looks to me like the DOVE `get_raven_loc()` would return a different directory than the HERON `get_raven_loc()` in the case of a pip installed raven, but as you explained, that shouldn't be an issue for my particular application for the function. The difference may not matter in general either, but it's hard for me to say.

I cleared my PYTHONPATH and am getting the expected results when trying to import `ravenframework` now (e.g., it fails), so that was definitely the issue. Removing ravenframework from the PYTHONPATH does cause other issues with running DOVE for me though. I'll send an invite for a Teams meeting, if that works for you, so we can discuss those (and also just for a general discussion of my recent work in DOVE).

**Comment by dylanjm** [comment]
We had a discussion and realized that we need to make sure DOVE and RAVEN are in the PYTHONPATH before tests are run. We decided to look into alternative methods to make sure that happens like either modifying the run_tests scripts or chainging the import logic. I will close this issue for now.
